### ISSUE TITLE
[FE] 코드 정리

### ISSUE THREAD

**Issue by hyejj19** [codestates-seb/seb40_main_004#421]
## Description

불필요한 코드 제거 및 컴포넌트 폴더 정리

## Todo

- [x] 사용하지 않는 변수 제거
- [x] 개발자 이름 -> 컴포넌트별로 폴더 분리, 경로 수정
- [x] atom 분리
- [x] interface 분리
- [x] tsconfig.json 설정 - https://www.typescriptlang.org/docs/handbook/module-resolution.html 참고하여 import 구문 정리

## ETC
- Conflict 방지를 위해 라이브 쉐어로 진행
